media:
  - name: files
    label: Files
    input: assets/files
    output: /assets/files
    categories: [document]
  - name: images
    label: Images
    input: assets/files/images
    output: /assets/files/images
    extensions: [png, webp, jpg, jpeg, gif, svg, webp]
content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [title, date, last_modified_date]
    fields:
      - name: date
        label: Date
        type: date
      - name: last_modified_date
        label: Last Modified Date
        type: date
      - name: title
        label: Title
        type: string
      - name: layout
        label: Layout
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: summaries
    label: Summaries
    type: collection
    path: '_summaries'
    view:
      fields: [title, date, last_modified_date]
    fields:
      - name: date
        label: Date
        type: date
      - name: last_modified_date
        label: Last Modified Date
        type: date
      - name: title
        label: Title
        type: string
      - name: layout
        label: Layout
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: articles
    label: Articles
    type: collection
    path: '_articles'
    view:
      fields: [title, date, last_modified_date]
    fields:
      - name: date
        label: Date
        type: date
      - name: last_modified_date
        label: Last Modified Date
        type: date
      - name: title
        label: Title
        type: string
      - name: layout
        label: Layout
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: photography
    label: Photography
    path: photography.md
    type: file
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: config
    label: Jekyll config
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: body
        label: Jekyll config
        type: rich-text
  - name: typst_collection
    label: Typst Collection
    path: typst_collection.md
    type: file
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Typst Collection
        type: rich-text
