site_name: Aaron PM
site_url: https://aaronmurniadi.github.io/
site_dir: docs
site_author: Aaron P. Murniadi
use_directory_urls: false

theme: 
    name: material
    features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
#    - navigation.indexes
    palette:
    - primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

docs_dir: source

pages:

extra_css:
    - css/extra.css

extra_javascript:
    - js/Hyphenopoly_config.js
    - js/Hyphenopoly.js

markdown_extensions:
    - toc:
        permalink: 
        separator: "_"
    - smarty
    - footnotes
    - tables
    - meta

plugins:
    - search:
        indexing: 'full'

extra:
  generator: false

copyright: Copyright &copy; 2017 - 2021 Aaron P. Murniadi
