name: Compile, Upload and Release Typst Documents
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating releases
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Find all Typst files
        id: find-typst
        run: |
          # Find all .typ files and create a list for the matrix
          typst_files=$(find . -name "*.typ" -type f | sed 's|^\./||' | jq -R -s -c 'split("\n")[:-1]')
          echo "typst_files=$typst_files" >> $GITHUB_OUTPUT
          
          # Also create a space-separated list for file uploads
          file_list=$(find . -name "*.typ" -type f | sed 's|^\./||' | sed 's|\.typ$|.pdf|' | tr '\n' ' ')
          echo "pdf_files=$file_list" >> $GITHUB_OUTPUT
      
      - name: Compile Typst files
        run: |
          # Install Typst
          curl -fsSL https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz | tar -xJ
          sudo mv typst-x86_64-unknown-linux-musl/typst /usr/local/bin/
          
          # Compile each .typ file found
          find . -name "*.typ" -type f | while read -r file; do
            echo "Compiling $file"
            typst compile "$file"
          done
      
      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-typst-documents
          path: "**/*.pdf"

      - name: Delete existing release and tag
        run: |
          # Delete existing release if it exists
          gh release delete latest --yes || true
          # Delete existing tag if it exists
          git push --delete origin latest || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Typst Documents
          files: "**/*.pdf"
          generate_release_notes: true