site_name: Aaron P. Murniadi
site_url: https://aaronmurniadi.github.io/
copyright: Copyright &copy; 2018 - 2022 Aaron P. Murniadi

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.betterem
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra_css:
  - stylesheets/extra.css


extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aaronmurniadi/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/aaronmurniadi
